Ammp 663 device based on dataloggers
ammpio/ammp-edge pull request #13
Opened 2020-08-31 14:49 UTC by judruizc

Hey @svet-b, here is the basic functionality for getting device-based readings up to the queues. Then the datapusher, depending on the endpoint -- api, mqtt, influx..is in charge of re-factoring the payload. I wrote some notes on the process:
- first: problem is that we were “losing” the association between devices and readings when we were writing to the queues. So the at the modifications at the datapusher was too late. We needed to keep this association up to the moment of writing to the queues (non-v and volatile)

- first approach was to separate reading the devices themselves from the shape/construction of the readout (the thing that was being written to the queues)
	This was very complicated as the jobs that read the devices (line 153+ get_readings) append the results to a readout_q and the readout is created on the spot using that. Hard to de-couple

-  second approach was to **modify the readout itself**, so it still contained the device data. Then the datapusher is in charge of reading it, and modifying it to best suit needs

- at the moment is only working for API endpoint, mqtt next

2020-08-31 22:00 UTC, svet-b reviewed
Thanks @judruizc ! Overall this looks like the right direction to me. In particular, I agree with changing the structure of the `readout` payload, and saving the full device-based readings in the new structure (while no longer attempting to make it "Influx-compatible).

Most of my comments are of a stylistic nature. I haven't dug into much detail on the changes in logic. To this end, could you share (maybe via another channel) an example `readout` that's generated in this way?

2020-09-01 09:20 UTC, judruizc commented
> Thanks @judruizc ! Overall this looks like the right direction to me. In particular, I agree with changing the structure of the `readout` payload, and saving the full device-based readings in the new structure (while no longer attempting to make it "Influx-compatible).
> 
> Most of my comments are of a stylistic nature. I haven't dug into much detail on the changes in logic. To this end, could you share (maybe via another channel) an example `readout` that's generated in this way?

A "Raw readout" how I call it, looks like this at the moment. It's not ideal because as you can see, it may contain several entries (i.e. dicts) for a single Device. This is specially true for the _logger_ (still unknown when reading many devices), because the _raw readout_ is constructed as the code goes: Once to get the Snap version, another to get the cpu/memory/etc.. and a last one to get the reading_duration. (I assumed the Snap reading and the reading_duration to be under _logger_.)
`{
  "time": "2020-09-01T09:14:00Z",
  "device_readings": [
    {
      "dev_id": "logger",
      "comms_lggr_snap_rev": 0
    },
    {
      "dev_id": "logger",
      "comms_lggr_boot_time": 1594463915,
      "comms_lggr_cpu_load": 0.39,
      "comms_lggr_mem_usage": 77
    },
    {
      "dev_id": "logger_strato",
      "comms_lggr_cpu_temp": 57.458,
      "comms_lggr_disk_usage": 62.2
    },
    {
      "dev_id": "logger",
      "reading_duration": 0.042691
    }
  ],
  "meta": {}
}`

2020-09-02 12:40 UTC, judruizc commented on Pipfile
> +python_version = "3.8"
The reason was that I only had 3.8 on my laptop's venvs.. so I wanted it to stop complaining, but of-course I meant to set it back (I already did, and installed a new venv with 3.6 locally)

2020-10-06 10:53 UTC, judruizc commented on src/ammp_edge.py
> +from reader.get_readings import get_readout
Should be fixed

2020-10-06 11:05 UTC, judruizc commented
Hey Svet, an update on this. So we get now the device-based and the older API format readouts:

Device-based
```
{
  "time": "2020-10-06T10:46:00Z",
  "snap_rev": 0,
  "reading_duration": 0.049848,
  "meta": {
    "config_id": "7e2fdcf"
  },
  "device_readings": [
    {
      "dev_id": "logger",
      "boot_time": 1599053217,
      "cpu_load": 0.45,
      "memory_usage": 73
    },
    {
      "dev_id": "logger_strato",
      "cpu_temp": 53.692,
      "disk_usage": 67.1
    }
  ]
}```

API older format
```
{
  "time": "2020-10-06T10:46:00Z",
  "meta": {
    "config_id": "7e2fdcf"
  },
  "fields": {
    "comms_lggr_boot_time": 1599053217,
    "comms_lggr_cpu_load": 0.45,
    "comms_lggr_cpu_temp": 53.692,
    "comms_lggr_disk_usage": 67.1,
    "comms_lggr_mem_usage": 73,
    "snap_rev": 0,
    "reading_duration": 0.049848,
    "reading_offset": 0
  }
}```

I wasn't sure what to do with the `snap_rev`, `reading_duration` and `reading_offset` in the device-based one.

2020-10-06 12:07 UTC, svet-b reviewed
Thanks Juan, these look good!

> I wasn't sure what to do with the `snap_rev`, `reading_duration` and `reading_offset` in the device-based one.
I think having them at the top level like that is fine. We will have a handler function within the MQTT listener that can decide what (if anything) to do with them.

2020-10-06 13:48 UTC, judruizc commented on src/data_mgmt/helpers/convert_to_api_payload.py
> +	readout['fields'].update({"snap_rev": readout['snap_rev']})
Thanks for the good tip. Adapted it.

2020-10-06 13:48 UTC, judruizc commented on src/reader/get_readings.py
> +    readout['meta'].update({'config_id': node.config.get('config_id', '')})
Also adapted

2020-10-07 15:47 UTC, judruizc commented
Hey Svet, so this is a sum-up of what is attempted here. 

1.  We needed to change the way readings were save to the internal queue. Before it saved it in the almost flat dict with all measurements taken under fields. That way we lost the **devices** info (i.e. who measured what). 
So what I did was mostly change that, to save it in a new _device-based readout format_. This is mostly done in the `get_readings.py` module. 
The new format looks like (`reading_offset `is added at the end, once is about to be pushed): 
```
{
  "time": "2020-10-06T10:46:00Z",
  "snap_rev": 0,
  "reading_duration": 0.049848,
  "meta": {
    "config_id": "7e2fdcf"
  },
  "device_readings": [
    {
      "dev_id": "logger",
      "boot_time": 1599053217,
      "cpu_load": 0.45,
      "memory_usage": 73
    },
    {
      "dev_id": "logger_strato",
      "cpu_temp": 53.692,
      "disk_usage": 67.1
    }
  ]
}
```
2. We needed to keep consistency API payload. For this, if the `datapusher.py` module detects we want to push to API, it uses the new module `convert_to_api_payload.py` that basically transforms the readout into the familiar way. 

3. The addition under `network_host_finder.py` is just to fix the 00:00:00:00 MAC issue.

2020-10-26 11:12 UTC, svet-b requested changes

2020-10-27 09:10 UTC, judruizc commented on src/data_mgmt/datapusher.py
> +            pub = self._mqtt_session.publish(f"a/{self._node.node_id}/data", json.dumps(readout_to_push), 1, False)
Didn't know about the extra spaces. I corrected to:
```
            MQTT_QOS = 1
            MQTT_RETAIN = False
            MQTT_PUB_SUCCESS = 0
            logger.debug(f"PUSH [MQTT]. Device-based readout: {readout_to_push}")
            pub = self._mqtt_session.publish(f"a/{self._node.node_id}/data",
                                             json.dumps(readout, separators=(',', ':')),
                                             qos=MQTT_QOS, retain=MQTT_RETAIN)
```

2020-10-27 09:10 UTC, judruizc commented on src/reader/helpers/network_host_finder.py
> +                if this_mac == '00:00:00:00:00:00':
Makes much sense. Should be corrected now

2020-10-27 09:11 UTC, judruizc commented on src/data_mgmt/datapusher.py
> +            self._mqtt_session = mqtt.Client(client_id="ammp", clean_session=False, transport="tcp")
Yeah I was a bit confused by this client_id. I'm using now the node id for it as you suggest:
`self._mqtt_session = mqtt.Client(client_id=self._node.node_id, clean_session=False, transport="tcp")`

2020-10-27 09:14 UTC, judruizc commented
Hey @svet-b , thanks for the feedback -- always giving me the "why" :) 

I hope most of these issues are corrected now. Please have a look when you can.

2020-11-10 15:30 UTC, merged